config/routes.rb
Rails.application.routes.draw do

  root to: 'orders#index'
  
  resources :orders
  resources :cup_add_ons
  resources :cups
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cup.rb
class Cup < ApplicationRecord
end

app/models/cup_add_on.rb
class CupAddOn < ApplicationRecord
end

app/models/order.rb
class Order < ApplicationRecord

  has_many :items, class_name: 'OrderItem', inverse_of: :order

  before_create :save_amount

  accepts_nested_attributes_for :items, allow_destroy: true


 def save_amount
total = 0
self.items.each do |item|
total += item.cup.price
item.add_ons.each do |add_on|
total += add_on.price
end
end
self.amount = total
end

end

app/models/order_item.rb
class OrderItem < ApplicationRecord
  belongs_to :order
  belongs_to :cup

  has_and_belongs_to_many :add_ons, class_name: 'CupAddOn', join_table: :order_item_add_ons, dependent: :destroy
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/cup_add_ons_controller.rb
class CupAddOnsController < ApplicationController
  before_action :set_cup_add_on, only: [:show, :edit, :update, :destroy]

  # GET /cup_add_ons
  # GET /cup_add_ons.json
  def index
    @cup_add_ons = CupAddOn.all
  end

  # GET /cup_add_ons/1
  # GET /cup_add_ons/1.json
  def show
  end

  # GET /cup_add_ons/new
  def new
    @cup_add_on = CupAddOn.new
  end

  # GET /cup_add_ons/1/edit
  def edit
  end

  # POST /cup_add_ons
  # POST /cup_add_ons.json
  def create
    File.open("public/images/#{cup_add_on_params[:image_url].original_filename}", "wb") do |f|
     f.write(cup_add_on_params[:image_url].read)
    end if cup_add_on_params[:image_url].present?

    @cup_add_on = CupAddOn.new(cup_add_on_params)
    @cup_add_on.image_url = "public/images/#{cup_add_on_params[:image_url].original_filename}" if cup_add_on_params[:image_url].present?

    respond_to do |format|
      if @cup_add_on.save
        format.html { redirect_to cup_add_ons_path, notice: 'Novo Adicional Salvo!' }
        format.json { render :show, status: :created, location: @cup_add_on }
      else
        format.html { render :new }
        format.json { render json: @cup_add_on.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /cup_add_ons/1
  # PATCH/PUT /cup_add_ons/1.json
  def update
    respond_to do |format|
      if @cup_add_on.update(cup_add_on_params)
        format.html { redirect_to cup_add_ons_path, notice: 'Adicional atualizado!' }
        format.json { render :show, status: :ok, location: @cup_add_on }
      else
        format.html { render :edit }
        format.json { render json: @cup_add_on.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /cup_add_ons/1
  # DELETE /cup_add_ons/1.json
  def destroy
    @cup_add_on.destroy
    respond_to do |format|
      format.html { redirect_to cup_add_ons_url, notice: 'Adicional apagado!' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_cup_add_on
      @cup_add_on = CupAddOn.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def cup_add_on_params
      params.require(:cup_add_on).permit(:name, :image_url, :price)
    end
end

app/controllers/cups_controller.rb
class CupsController < ApplicationController
  before_action :set_cup, only: [:show, :edit, :update, :destroy]

  # GET /cups
  # GET /cups.json
  def index
    @cups = Cup.all
  end

  # GET /cups/1
  # GET /cups/1.json
  def show
  end

  # GET /cups/new
  def new
    @cup = Cup.new
  end

  # GET /cups/1/edit
  def edit
  end

  # POST /cups
  # POST /cups.json
  def create
    File.open("public/images/#{cup_params[:image_url].original_filename}", "wb") do |f|
     f.write(cup_params[:image_url].read)
    end if cup_params[:image_url].present?

    @cup = Cup.new(cup_params)
    @cup.image_url = "public/images/#{cup_params[:image_url].original_filename}" if cup_params[:image_url].present?

    respond_to do |format|
      if @cup.save
        format.html { redirect_to cups_path, notice: 'Novo copo criado!' }
        format.json { render :show, status: :created, location: @cup }
      else
        format.html { render :new }
        format.json { render json: @cup.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /cups/1
  # PATCH/PUT /cups/1.json
  def update
    File.open("public/images/#{cup_params[:image_url].original_filename}", "wb") do |f|
     f.write(cup_params[:image_url].read)
    end if cup_params[:image_url].present?

    respond_to do |format|
      if @cup.update(cup_params)
        if cup_params[:image_url].present?
          @cup.image_url = "public/images/#{cup_params[:image_url].original_filename}"
          @cup.save!
        end

        format.html { redirect_to cups_path, notice: 'Copo atualizado!.' }
        format.json { render :show, status: :ok, location: @cup }
      else
        format.html { render :edit }
        format.json { render json: @cup.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /cups/1
  # DELETE /cups/1.json
  def destroy
    @cup.destroy
    respond_to do |format|
      format.html { redirect_to cups_url, notice: 'Copo excluído!' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_cup
      @cup = Cup.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def cup_params
      params.require(:cup).permit(:name, :image_url, :price)
    end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  before_action :set_order, only: [:show, :edit, :update, :destroy]

  # GET /orders
  # GET /orders.json
  def index
    @orders = Order.all
  end

  # GET /orders/1
  # GET /orders/1.json
  def show
  end

  # GET /orders/new
  def new
    @order = Order.new
    item = @order.items.build
    # item.add_ons.build
  end

  # GET /orders/1/edit
  def edit
  end

 
  # POST /orders
  # POST /orders.json
  def create
    @order = Order.new(order_params)

    respond_to do |format|
      if @order.save
        format.html { redirect_to @order, notice: 'Novo Pedido Criado!' }
        format.json { render :show, status: :created, location: @order }
      else
        format.html { render :new }
        format.json { render json: @order.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /orders/1
  # PATCH/PUT /orders/1.json
  def update
    respond_to do |format|
      if @order.update(order_params)
        format.html { redirect_to @order, notice: 'Pedido atualizado!' }
        format.json { render :show, status: :ok, location: @order }
      else
        format.html { render :edit }
        format.json { render json: @order.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /orders/1
  # DELETE /orders/1.json
  def destroy
    @order.destroy
    respond_to do |format|
      format.html { redirect_to orders_url, notice: 'Pedido cancelado!' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_order
      @order = Order.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def order_params
      params.require(:order).permit(:customer, :amount, items_attributes: [:id, :cup_id, :_destroy, add_on_ids: []])
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cup_add_ons_helper.rb
module CupAddOnsHelper
end

app/helpers/cups_helper.rb
module CupsHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/views/cup_add_ons/_form.html.erb
<%= form_for(cup_add_on) do |f| %>
  <% if cup_add_on.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(cup_add_on.errors.count, "error") %> prohibited this cup_add_on from being saved:</h2>

      <ul>
      <% cup_add_on.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :name, "Nome" %>
    <%= f.text_field :name, class: 'form-control' %>
  </div>


  <div class="row">
    <div class="col-lg-6">
      <div class="form-group">
        <%= f.label :image_url, "Imagem" %>
        <%= f.file_field :image_url, class: 'form-control' %>
      </div>
    </div>

    <div class="col-lg-6">
      <div class="form-group">
        <%= f.label :price, "Preço" %>
        <%= f.number_field :price, class: 'form-control', step: '0.01' %>
      </div>
    </div>
  </div>

  <div class="actions">
    <%= f.submit "Salvar", :class => "btn btn-success" %>
    <p>
  </div>
<% end %>

app/views/cup_add_ons/edit.html.erb
<div class="col-lg-8 col-centered">
  <legend>Novo Copo</legend>

  <%= render 'form', cup_add_on: @cup_add_on %>
</div>

app/views/cup_add_ons/index.html.erb
<div class="col-lg-8 col-centered">
  <p id="notice"><%= notice %></p>

  <legend>Adicionais</legend>

  <table class="table table-hover">
    <thead>
      <tr>
        <th>Nome</th>
        <th>Imagem </th>
        <th>Preço</th>
        <th colspan="3"></th>
      </tr>
    </thead>

    <tbody>
      <% @cup_add_ons.each do |cup_add_on| %>
        <tr>
          <td><%= cup_add_on.name %></td>
          <td> <img src=<%= asset_path(cup_add_on.image_url.gsub('public/', '')) %> width="80" height="80"> </td>          <td><%= cup_add_on.price %></td>
          <td><%= link_to 'Mostrar', cup_add_on %></td>
          <td><%= link_to 'Editar', edit_cup_add_on_path(cup_add_on) %></td>
          <td><%= link_to 'Excluir', cup_add_on, method: :delete, data: { confirm: 'Tem certeza que deseja excluir?' } %></td>
        </tr>
      <% end %>
    </tbody>
  </table>

  <br>

  <%= link_to 'Novo Adicional', new_cup_add_on_path, :class => "btn btn-success" %>

</div>

app/views/cup_add_ons/new.html.erb
<div class="col-lg-8 col-centered">
  <legend>Novo Adicional</legend>

  <%= render 'form', cup_add_on: @cup_add_on %>

  <%= link_to 'Voltar', cup_add_ons_path %>
</div>

app/views/cup_add_ons/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @cup_add_on.name %>
</p>

<p>
  <strong>Image:</strong>
  <%= image_tag(asset_path(@cup_add_on.image_url.gsub('public/', ''))) if @cup_add_on.image_url %>
</p>

<p>
  <strong>Price:</strong>
  <%= @cup_add_on.price %>
</p>

<%= link_to 'Editar', edit_cup_add_on_path(@cup_add_on) %> |
<%= link_to 'Voltar', cup_add_ons_path %>

app/views/cups/_form.html.erb
<%= form_for(cup, multipart: true) do |f| %>
  <% if cup.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(cup.errors.count, "error") %> prohibited this cup from being saved:</h2>

      <ul>
      <% cup.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :name, "Nome" %>
    <%= f.text_field :name, class: 'form-control' %>
  </div>


  <div class="row">
    <div class="col-lg-6">
      <div class="form-group">
        <%= f.label :image_url, "Imagem" %>
        <%= f.file_field :image_url, class: 'form-control' %>
      </div>
    </div>

    <div class="col-lg-6">
      <div class="form-group">
        <%= f.label :price, "Preço"%>
        <%= f.number_field :price, class: 'form-control', step: '0.01' %>
      </div>
    </div>
  </div>

  <div class="actions">
  <p>
    <%= f.submit "Salvar", :class => "btn btn-success" %>
    <p>
  
  </div>
<% end %>

app/views/cups/edit.html.erb
<div class="col-lg-8 col-centered">
  <legend>Editar Copo</legend>

  <%= render 'form', cup: @cup %>
</div>

app/views/cups/index.html.erb
<div class="col-lg-8 col-centered">
  <p id="notice"><%= notice %></p>

  <legend>Copos</legend>

  <table class="table table-hover">
    <thead>
      <tr>
        <th>Nome</th>
        <th>Imagem</th>
        <th>Preço</th>
        <th colspan="3"></th>
      </tr>
    </thead>

    <tbody>
      <% @cups.each do |cup| %>
        <tr>
          <td><%= cup.name %></td>
          <td> <img src=<%= asset_path(cup.image_url.gsub('public/', '')) %> width="50" height="80"> </td>
          <td><%= cup.price %></td>
          <td><%= link_to 'Mostrar', cup %></td>
          <td><%= link_to 'Editar', edit_cup_path(cup) %></td>
          <td><%= link_to 'Excluir', cup, method: :delete, data: { confirm: 'Tem certeza que deseja excluir?' } %></td>
        </tr>
      <% end %>
    </tbody>
  </table>

  <br>

  <%= link_to 'Novo Copo', new_cup_path, :class => "btn btn-success" %>

</div>

app/views/cups/new.html.erb
<div class="col-lg-8 col-centered">
  <legend>Novo Copo</legend>

  <%= render 'form', cup: @cup %>

  <%= link_to 'Cancelar', cups_path, class: 'btn btn-default' %>
</div>

app/views/cups/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Descrição:</strong>
  <%= @cup.name %>
</p>

<p >
  <strong>Imagem:</strong>
  
  <%= image_tag(asset_path(@cup.image_url.gsub('public/', ''))) if @cup.image_url %>
 
</p>

<p>
  <strong>Pre&ccedil;o:</strong>
  <%= @cup.price %>
</p>

<%= link_to 'Editar', edit_cup_path(@cup) %> |
<%= link_to 'Voltar', cups_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RotaAcai</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>


    <nav class="navbar navbar-default" class="navBar-cc">
      <div  class="container-fluid">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
           <img src= "/images/logoacai.png" class="img-responsive" alt="Cinque Terre" width="100" height="50"> 
          <!-- <a class="navbar-brand" href="#">Rota do A&ccedil;a&iacute;</a> -->
        </div>

        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1" style="">
          <ul class="nav navbar-nav">
            <li class="<%= 'active' if params[:controller] == 'cups' %>"><%= link_to 'Copos', cups_path %></li>
            <li class="<%= 'active' if params[:controller] == 'cup_add_ons' %>"><%= link_to 'Adicionais', cup_add_ons_path %></li>
            <li class="<%= 'active' if params[:controller] == 'oerders' %>"><%= link_to 'Pedidos', orders_path %></li>
          </ul>
          
          <!--
          <ul class="nav navbar-nav navbar-right">
            <li><a href="#">Link</a></li>
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Dropdown <span class="caret"></span></a>
              <ul class="dropdown-menu">
                <li><a href="#">Action</a></li>
                <li><a href="#">Another action</a></li>
                <li><a href="#">Something else here</a></li>
                <li role="separator" class="divider"></li>
                <li><a href="#">Separated link</a></li>
              </ul>
            </li>
          </ul>
        -->
        </div><!-- /.navbar-collapse -->
      </div><!-- /.container-fluid -->
    </nav>



    <%= yield %>

  </body>
</html>

app/views/orders/_form.html.erb
<%= form_for(order) do |f| %>
  <% if order.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(order.errors.count, "error") %> prohibited this order from being saved:</h2>

      <ul>
      <% order.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label  :Cliente %>
    <%= f.text_field :customer, class: 'form-control' %>
  </div>

  <legend>Itens</legend>

  <%= f.nested_fields_for :items do |item_form| %>
    
    <div class="panel panel-default">
      <div class="panel-body">
        
        <% Cup.all.each do |cup| %>
          <div class="col-lg-4"> 
            <div class="radio" class="cc-selector" > <!-- class="cc-selector" -->
              <%= item_form.radio_button :cup_id, cup.id %>
              <%= item_form.label :cup_id, cup.name %>
             <!-- <%= item_form.label :cup_id, cup.name, style: " text-align: center; background-image: url('#{cup.image_url ? cup.image_url.gsub('public', '') : ''}')", class: "drinkcard-cc" %> -->
            </div>
          </div>
        <% end %>

        <!--
        <%= item_form.collection_check_boxes :add_on_ids, CupAddOn.all, :id, :name %> 
        -->
        
      <%= item_form.collection_check_boxes(:add_on_ids, CupAddOn.all, :id, :name) do |b| %>
        <%= b.label class:"drinkcard-cc" do %>
         <%=b.check_box + b.text %>

        <%end%>
    <% end %>
      

      </div>
    </div>
    
    <%= item_form.remove_nested_fields_link "Remover Pedido" %>
  <% end %>
  <%= f.add_nested_fields_link :items, "Adicionar mais copos"  %>

  <div class="actions">
  <p>
    <%= f.submit "Salvar Pedido", :class => "btn btn-success" %>
  <p>
    
    </div>
  
  <!--
    <div class="cc-selector">
        <input id="visa" type="radio" name="credit-card" value="visa" />
        <label class="drinkcard-cc visa" for="visa"></label>
    </div>
  -->

<% end %>

app/views/orders/edit.html.erb
<div class="col-lg-8 col-centered">
  <legend>Editar Pedido</legend>

  <%= render 'form', order: @order %>

  <%= link_to 'Mostrar', @order %> |
  <%= link_to 'Voltar', orders_path %>
</div>

app/views/orders/index.html.erb
<div class="col-lg-8 col-centered">
  <p id="notice"><%= notice %></p>

  <legend>Pedidos</legend>

  <table class="table table-hover">
    <thead>
      <tr>
        <th>Cliente</th>
        <th>Valor Total</th>
        <th colspan="3"></th>
      </tr>
    </thead>

    <tbody>
      <% @orders.each do |order| %>
        <tr>
          <td><%= order.customer %></td>
          <td><%= order.amount %></td>
          <td><%= link_to 'Mostrar', order %></td>
          <td><%= link_to 'Editar', edit_order_path(order) %></td>
          <td><%= link_to 'Excluir', order, method: :delete, data: { confirm: 'Tem certeza que deseja excluir?' } %></td>
        </tr>
      <% end %>
    </tbody>
  </table>

  <br>

  <%= link_to 'Novo Pedido', new_order_path, :class => "btn btn-success" %>
</div>

app/views/orders/new.html.erb
<div class="col-lg-8 col-centered">
  <legend>Novo Pedido</legend>

  <%= render 'form', order: @order %>

  <%= link_to 'Voltar', orders_path %>
</div>

app/views/orders/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Cliente:</strong>
  <%= @order.customer %>
</p>

<p>

  <strong>Pedido:</strong>
  	  
          <% @order.items.each do |item|  %>
          <p>
          <strong>Copo:</strong>
              <%= item.cup.name%>
              </p>
              <p>
              <strong>Adicionais:</strong>
              </p>
              <% item.add_ons.each do |add_on|  %>
                | <%= add_on.name%>
      <% end %>         
      <p></p>
    <% end %>


</p>

<p>
  <strong>Total:</strong>
  <%= @order.amount %>
</p>
<p>
<a onclick='window.print(); return false;' class='btn btn-success'>Imprimir</a>
</p>
<%= link_to 'Editar', edit_order_path(@order) %> |
<%= link_to 'Voltar', orders_path %>